server:
    port: 8585
    error:
        include-stacktrace: never
jms:
    jwt:
        security:
            enabled: true
        timezone: "America/Argentina/Buenos_Aires"
        issuer: "www.sort-boks.com"
        token:
            auth: 
                path: "/v1.0/oauth/client_credential/accesstoken"
            secret: "marcelo es lo mejor"
            expires-in: 3600 # seconds
        excluded:
            path: "/v1.0/multi, /v1.0/otra"

