server: 
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: http://localhost:8761/eureka

spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routers:
        - id: company-service
          uri: http://company-service
          predicates:
            - http=/company/**
        - id: truck-service
          uri: lb://truck-service
          predicates:
            - Path=/truck/**
        - id: van-service
          uri: http://van-service
          predicates:
            - Path=/van/**