server: 
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routers:
        - id: company-service
          uri: lb://company-service/
          predicates:
            - Path=/company/**
        - id: truck-service
          uri: lb://truck-service/
          predicates:
            - Path=/truck/**
        - id: van-service
          uri: lb://van-service/
          predicates:
            - Path=/van/**