server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: gateway
                    uri: https://github.com/msaporito61/cursoSpringBoot
                    search-paths: microservicios/config-data
    application:
        name: configserver
